package io.github.zhangrongshun.util.codec;

import java.nio.charset.StandardCharsets;

public class Base36 extends BaseN {

    public Base36() {
        super(36);
    }

    public static void main(String[] args) {
        byte[] bytes = "zhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshunzhangrongshun".getBytes();
//        String x = Hex.encodeHexString(bytes);
//        System.out.println(x);
        String encode = encode(bytes);
        System.out.println(encode);
        System.out.println(new String(decode(encode), StandardCharsets.UTF_8));
    }

}
